# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,4,6,8]],np.int64)

In [3]:
myarr

array([[2, 4, 6, 8]])

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0,1]

np.int64(4)

In [8]:
myarr[0,1]=45

In [9]:
myarr

array([[ 2, 45,  6,  8]])

# Array Creation : Conversion from other python structures

In [11]:
listarr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarr.dtype

dtype('int64')

In [14]:
listarr.shape

(3, 3)

In [15]:
listarr.size

9

# Intrinsic Numpy Array Creation (arange,zeros,ones,etc..)

In [16]:
zeroarr=np.zeros((2,5)) #create an array of 2 rows and 5 columns filled with zeroes

In [17]:
zeroarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeroarr.dtype

dtype('float64')

In [19]:
zeroarr.shape

(2, 5)

In [20]:
rngarr=np.arange(10)

In [21]:
rngarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
for num in rngarr:
    print(num ,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [25]:
lspace=np.linspace(1,10,10) #creates an array of ten elements from which are linerarly spaced linspace(startele,endele,no_of_ele)

In [26]:
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
emp=np.empty((4,5)) #creates an array of 4 rows and 5 columns which are filled with random numbers

In [29]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.11261434e-306,
        1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306],
       [1.33511969e-306, 1.78022342e-306, 1.05700345e-307,
        1.24610383e-306, 9.34593493e-307],
       [8.90104918e-307, 1.69119602e-306, 1.33511222e-306,
        2.22522596e-306, 1.42410974e-306]])

In [32]:
#creates an identity matrix of specified size.An identity matrix is a matrix whose diagonal elements are 1 and all elements are zeroes
idearr=np.identity(3) 

In [31]:
idearr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Important - reshape method

In [33]:
elearr=np.arange(99)

In [34]:
elearr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
elearr=elearr.reshape(3,33) #reshapes the array into three rows with each row containing 33 elements

In [42]:
elearr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
elearr.shape

(3, 33)

In [44]:
elearr=elearr.ravel() #reshapes as a 1-d array

In [45]:
elearr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Numpy Axis

In [46]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [47]:
ar=np.array(x)

In [48]:
ar.sum(axis=0) 

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.T #returns transpose of a matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.ndim #return dimension of an array

2

In [52]:
ar.size #returns number of elements in array

9

In [54]:
ar.nbytes #returns the total number of bytes your array consumed

72

# Important - argmax()  and argmin()

In [57]:
one = np.array([1,32,12,45,99,21,32]) # argmax() method returns the maximum element index in an array

In [56]:
one.argmax()

np.int64(4)

In [58]:
one.argmin()

np.int64(0)

In [59]:
one.argsort() # returns the array of indices of sorted array

array([0, 2, 5, 1, 6, 3, 4])

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [62]:
ar.max() #returns maximum element from array

np.int64(7)

In [63]:
ar.min() #returns minimum element from array

np.int64(0)

In [64]:
np.where(ar>2)

(array([0, 1, 1, 1, 2]), array([2, 0, 1, 2, 0]))